name: Remote System Health Check

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run System Manager
        run: ./system_manager.sh
